{% set name = "open-cravat" %}
{% set version = "3.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/3c/98/e701f5a5193e59cfae18b8a45241664f048e1b83984d6151c6330bfb8051/open_cravat-3.2.0.tar.gz
  sha256: 6572c4f9705e97c9b2cc7dd44253bfabab4fa812721ba7ffa86c3672a015a76f

build:
  number: 0
  entry_points:
    - oc=cravat.oc:main
  noarch: python
  script: {{PYTHON}} -m pip install . -vvv --no-build-isolation --no-deps --no-cache-dir
  run_exports:
    - {{ pin_subpackage('open-cravat', max_pin="x") }}

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
  run:
    - aiohttp <4.0.0
    - aiosqlite
    - biopython
    - chardet >=3.0.4,<6.0.0
    - intervaltree
    - markdown
    - mpmath
    - nest-asyncio
    - openpyxl
    - oyaml
    - psutil
    - pyliftover
    - python >=3.9
    - setuptools
    - pyyaml
    - requests
    - requests-toolbelt
    - twobitreader
    - websockets
    - xlsxwriter
    - pyvcf3
    - looseversion
    - packaging >=25.0.0
    - flask
    - paste
    - waitress
    - whitenoise
    - flask-caching
    - cachelib
    - celery
    - cryptography

test:
  imports:
    - cravat

about:
  home: "https://www.opencravat.org"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "OpenCRAVAT - variant analysis toolkit"
  doc_url: https://github.com/KarchinLab/open-cravat/wiki
  dev_url: https://github.com/KarchinLab/open-cravat

extra:
  recipe-maintainers:
    - cvaske
    - kmoad
    - rachelkarchin
    - skanderson
