package:
  name: glyco-csdb2snfg
  version: "0.2.0"

source:
  url: https://files.pythonhosted.org/packages/43/32/29d2606a30ae0fb103544da3e9a99e83a67049a997d258b73cce6efc4ca3/glyco_csdb2snfg-0.2.0.tar.gz
  sha256: d509fbd0d7ba227879437aa03728c4cd827a15f9cc2ee6a9b9e98b5c78656b13

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  run_exports:
    - {{ pin_subpackage("glyco-csdb2snfg", max_pin="x.x") }}

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - numpy >=1.21
    - matplotlib-base >=3.5
    - python-pptx >=0.6.21

test:
  imports:
    - csdb2snfg
  commands:
    - csdb2snfg --help

about:
  home: https://github.com/sosyphe/glyco-csdb2snfg
  license: MIT
  license_file: LICENSE
  summary: "A Python parser for converting Glyco CSDB format to SNFG drawings"
