{% set name = "chaff" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/clintval/{{ name }}/archive/{{ version }}.tar.gz
  sha256: e47af6a6dcba9b220639ac7133455a338d177cc69775d9432abb02f010628917

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: "https://github.com/clintval/{{ name }}"
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: "Flag somatic variant calls that are library-preparation artifacts."
  dev_url: "https://github.com/clintval/{{ name }}"
  doc_url: "https://github.com/clintval/{{ name }}/blob/{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - clintval
