{% set name = "harmonypy" %}
{% set version = "2.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "e255c927848564b2198c4b6d09de9402f5ab10e92dcb1be6f8a49164190b4a5c"

build:
  number: 0
  skip: True  # [py < 39]
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake >=3.15
    - make
    - ninja
  host:
    - pip
    - python
    - armadillo
    - scikit-build-core >=0.10
    - nanobind >=2.0
    - libopenblas  # [linux]
  run:
    - numpy
    - python
    - libopenblas  # [linux]

test:
  imports:
    - harmonypy

about:
  home: "https://github.com/slowkow/harmonypy"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: "A data integration algorithm."
  dev_url: "https://github.com/slowkow/harmonypy"
  doc_url: "https://portals.broadinstitute.org/harmony"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - pinin4fjords
